// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

// The GitHub Base API URL
func GetBaseUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "github:baseUrl")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "GITHUB_BASE_URL").(string); ok {
		return dv
	}
	return v
}

// Whether to run outside an organization.
func GetIndividual(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "github:individual")
}

// Whether server should be accessed without verifying the TLS certificate.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "github:insecure")
}

// The GitHub organization name to manage. If `individual` is false, organization is required.
func GetOrganization(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "github:organization")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "GITHUB_ORGANIZATION").(string); ok {
		return dv
	}
	return v
}

// The OAuth token used to connect to GitHub.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "github:token")
	if err == nil {
		return v
	}
	if dv, ok := getEnvOrDefault("", nil, "GITHUB_TOKEN").(string); ok {
		return dv
	}
	return v
}
