// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package github

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Use this data source to retrieve the collaborators for a given repository.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/d/collaborators.html.markdown.
func LookupCollaborators(ctx *pulumi.Context, args *GetCollaboratorsArgs) (*GetCollaboratorsResult, error) {
	inputs := make(map[string]interface{})
	if args != nil {
		inputs["affiliation"] = args.Affiliation
		inputs["owner"] = args.Owner
		inputs["repository"] = args.Repository
	}
	outputs, err := ctx.Invoke("github:index/getCollaborators:getCollaborators", inputs)
	if err != nil {
		return nil, err
	}
	return &GetCollaboratorsResult{
		Affiliation: outputs["affiliation"],
		Collaborators: outputs["collaborators"],
		Owner: outputs["owner"],
		Repository: outputs["repository"],
		Id: outputs["id"],
	}, nil
}

// A collection of arguments for invoking getCollaborators.
type GetCollaboratorsArgs struct {
	// Filter collaborators returned by their affiliation. Can be one of: `outside`, `direct`, `all`.  Defaults to `all`.
	Affiliation interface{}
	// The organization that owns the repository.
	Owner interface{}
	// The name of the repository.
	Repository interface{}
}

// A collection of values returned by getCollaborators.
type GetCollaboratorsResult struct {
	Affiliation interface{}
	// An Array of GitHub collaborators.  Each `collaborator` block consists of the fields documented below.
	Collaborators interface{}
	Owner interface{}
	Repository interface{}
	// id is the provider-assigned unique ID for this managed resource.
	Id interface{}
}
