// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package github

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a resource to manage GitHub repository collaborator invitations.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/r/user_invitation_accepter.html.markdown.
type UserInvitationAccepter struct {
	s *pulumi.ResourceState
}

// NewUserInvitationAccepter registers a new resource with the given unique name, arguments, and options.
func NewUserInvitationAccepter(ctx *pulumi.Context,
	name string, args *UserInvitationAccepterArgs, opts ...pulumi.ResourceOpt) (*UserInvitationAccepter, error) {
	if args == nil || args.InvitationId == nil {
		return nil, errors.New("missing required argument 'InvitationId'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["invitationId"] = nil
	} else {
		inputs["invitationId"] = args.InvitationId
	}
	s, err := ctx.RegisterResource("github:index/userInvitationAccepter:UserInvitationAccepter", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &UserInvitationAccepter{s: s}, nil
}

// GetUserInvitationAccepter gets an existing UserInvitationAccepter resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserInvitationAccepter(ctx *pulumi.Context,
	name string, id pulumi.ID, state *UserInvitationAccepterState, opts ...pulumi.ResourceOpt) (*UserInvitationAccepter, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["invitationId"] = state.InvitationId
	}
	s, err := ctx.ReadResource("github:index/userInvitationAccepter:UserInvitationAccepter", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &UserInvitationAccepter{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *UserInvitationAccepter) URN() *pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *UserInvitationAccepter) ID() *pulumi.IDOutput {
	return r.s.ID()
}

// ID of the invitation to accept
func (r *UserInvitationAccepter) InvitationId() *pulumi.StringOutput {
	return (*pulumi.StringOutput)(r.s.State["invitationId"])
}

// Input properties used for looking up and filtering UserInvitationAccepter resources.
type UserInvitationAccepterState struct {
	// ID of the invitation to accept
	InvitationId interface{}
}

// The set of arguments for constructing a UserInvitationAccepter resource.
type UserInvitationAccepterArgs struct {
	// ID of the invitation to accept
	InvitationId interface{}
}
