# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from . import utilities, tables

class GetIPRangesResult:
    """
    A collection of values returned by getIPRanges.
    """
    def __init__(__self__, gits=None, hooks=None, importers=None, pages=None, id=None):
        if gits and not isinstance(gits, list):
            raise TypeError("Expected argument 'gits' to be a list")
        __self__.gits = gits
        """
        An Array of IP addresses in CIDR format specifying the Git servers.
        """
        if hooks and not isinstance(hooks, list):
            raise TypeError("Expected argument 'hooks' to be a list")
        __self__.hooks = hooks
        """
        An Array of IP addresses in CIDR format specifying the addresses that incoming service hooks will originate from.
        """
        if importers and not isinstance(importers, list):
            raise TypeError("Expected argument 'importers' to be a list")
        __self__.importers = importers
        """
        An Array of IP addresses in CIDR format specifying the A records for GitHub Importer.
        """
        if pages and not isinstance(pages, list):
            raise TypeError("Expected argument 'pages' to be a list")
        __self__.pages = pages
        """
        An Array of IP addresses in CIDR format specifying the A records for GitHub Pages.
        """
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        __self__.id = id
        """
        id is the provider-assigned unique ID for this managed resource.
        """
class AwaitableGetIPRangesResult(GetIPRangesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetIPRangesResult(
            gits=self.gits,
            hooks=self.hooks,
            importers=self.importers,
            pages=self.pages,
            id=self.id)

def get_ip_ranges(opts=None):
    """
    Use this data source to retrieve information about a GitHub's IP addresses.

    > This content is derived from https://github.com/terraform-providers/terraform-provider-github/blob/master/website/docs/d/ip_ranges.html.markdown.
    """
    __args__ = dict()

    if opts is None:
        opts = pulumi.ResourceOptions()
    if opts.version is None:
        opts.version = utilities.get_version()
    __ret__ = pulumi.runtime.invoke('github:index/getIPRanges:getIPRanges', __args__, opts=opts).value

    return AwaitableGetIPRangesResult(
        gits=__ret__.get('gits'),
        hooks=__ret__.get('hooks'),
        importers=__ret__.get('importers'),
        pages=__ret__.get('pages'),
        id=__ret__.get('id'))
