// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTeam(args: GetTeamArgs, opts?: pulumi.InvokeOptions): Promise<GetTeamResult> & GetTeamResult {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    const promise: Promise<GetTeamResult> = pulumi.runtime.invoke("github:index/getTeam:getTeam", {
        "slug": args.slug,
    }, opts);

    return pulumi.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking getTeam.
 */
export interface GetTeamArgs {
    readonly slug: string;
}

/**
 * A collection of values returned by getTeam.
 */
export interface GetTeamResult {
    readonly description: string;
    readonly members: string[];
    readonly name: string;
    readonly permission: string;
    readonly privacy: string;
    readonly slug: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
